import BaseTheme from '../themes/BaseTheme';
import { pick } from 'lodash';

const allEvents = [
    'onAbort',
    'onAnimationStart',
    'onAnimationEnd',
    'onAnimationIteration',
    'onBlur',
    'onChange', 
    'onClick',
    'onCompositionEnd',
    'onCompositionStart',
    'onCompositionUpdate',
    'onContextMenu',
    'onCopy',
    'onCut',
    'onDoubleClick',
    'onDrag',
    'onDragEnd',
    'onDragEnter',
    'onDragLeave',
    'onDragOver',
    'onDragStart',
    'onDrop',
    'onError',
    'onFocus',
    'onGotPointerCapture',
    'onHover',
    'onInput',
    'onInvalid',
    'onLoad',
    'onLostPointerCapture',
    'onKeyDown',
    'onKeyPress',
    'onKeyUp',
    'onMouseDown',
    'onMouseEnter',
    'onMouseLeave',
    'onMouseMove',
    'onMouseOut',
    'onMouseOver',
    'onMouseUp',
    'onPaste',
    'onPointerDown',
    'onPointerMove',
    'onPointerUp',
    'onPointerCancel',
    'onPointerEnter',
    'onPointerLeave',
    'onPointerOver',
    'onPointerOut',
    
    'onRateChange',
    'onReset',
    'onScroll',
    'onSeeked',
    'onSeeking',
    'onSelect',
    'onStalled',
    'onSubmit',
    'onSuspend',
    
    'onTimeUpdate',
    'onToggle',
    'onTouchCancel',
    'onTouchEnd',
    'onTouchMove',
    'onTouchStart',
    'onTransitionEnd',
    'onVolumeChange',
    'onWaiting',
    'onWheel',

'onCanPlay',
'onCanPlayThrough',
'onDurationChange',
'onEmptied',
'onEncrypted',
'onEnded',
'onError',
'onLoadedData',
'onLoadedMetadata',
'onLoadStart',
'onPause',
'onPlay',
'onPlaying',
'onProgress',
];

export const getClassName = (baseClass, className, isDarkMode) => {
    const darkModeClass = isDarkMode ? ' is-dark-mode' : '';
    const overrideClass = className ? ` ${className}` : '';
    return `${baseClass}${darkModeClass}${overrideClass}`;
};

export const getBaseStyle = (overrides) =>
    Object.assign({}, BaseTheme, overrides);

export const extractEvents = (props) => pick(props, allEvents);
